config/routes.rb
Rails.application.routes.draw do
  resources :families
  resources :flowers

  root to: 'flowers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/family.rb
class Family < ApplicationRecord
end

app/models/flower.rb
class Flower < ApplicationRecord
  belongs_to :family

  validates :name, presence: true
  validates :family, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  def index
    @flowers = Flower.all
  end

  def new
    @families = Family.all
    @flower = Flower.new
  end

  def create
    @flower = Flower.create(flower_params)
    @families = Family.all
    if @flower.valid?
      redirect_to flowers_path
      flash[:notice] = "Flower was successfully created."
    else
      flash.now[:notice] = "Unable to create flower"
      render :new
    end
  end

  private
  def flower_params
    params.require(:flower).permit([:edible, :family_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/views/flowers/index.html.haml
%h1 Flowers

%ul
  - @flowers.each do |flower|
    %ul= flower.name

%div
= link_to "Add a Flower", new_flower_path

app/views/flowers/new.html.haml
%h1 Add a Flower

.container
  .row
    .col-xs-4.offset.xs-4
      - if @flower.errors.full_messages.length > 0
        .alert.alert-danger
          %h4.alert-heading There were some problems saving the form.
          %ul
            - @flower.errors.full_messages.each do |message|
              %li= message

      .well
        = form_for @flower do |f|
          .form-group
            = f.label :name
            = f.text_field :name, class: 'form-control'

          .form-group
            = f.label :edible
            = f.check_box :edible, class: 'form-control'

          .form-group
            = f.label :color
            = f.text_field :color, class: 'form-control'

          .form-group
            = f.label :family_id
            = f.select :family_id, options_from_collection_for_select(@families, :id, :name), class: 'form-control'

          .form-group
            = f.submit "Save", class: 'btn btn-primary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DebuggingExercise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-warning"><%= flash[:notice] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>